apiVersion: apps/v1
kind: Deployment
metadata:
  name: vosk
spec:
  selector:
    matchLabels:
      app: vosk
  template:
    metadata:
      labels:
        app: vosk
    spec:
      containers:
      - name: vosk
        image: alphacep/kaldi-en:latest
        resources:
          limits:
            memory: "1024Mi"
            cpu: "500m"
        ports:
        - containerPort: 2700
---
apiVersion: v1
kind: Service
metadata:
  name: vosk-svc
spec:
  selector:
    app: vosk
  ports:
  - port: 2700
    targetPort: 2700
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: vosk-ingress
  labels:
    name: vosk
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    nginx.ingress.kubernetes.io/server-snippets: |
      location / {
        proxy_set_header Upgrade $http_upgrade;
        proxy_http_version 1.1;
        proxy_set_header X-Forwarded-Host $http_host;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-For $remote_addr;
        proxy_set_header Host $host;
        proxy_set_header Connection "upgrade";
        proxy_cache_bypass $http_upgrade;
      }
spec:
  tls:
  - hosts:
    - stt.example.com
    secretName: stt-vosk-tls
  rules:
  - host: stt.example.com
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          serviceName: vosk-svc
          servicePort: 2700